# Generated by Django 4.2.27 on 2025-12-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="password",
            field=models.CharField(blank=True, max_length=100, verbose_name="비밀번호"),
        ),
    ]
